#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDM_INPUT_LIST_MENU                     33
#define IDM_TRAY_CONTEXTMENU                    34
#define IDR_ACTABLE                             65
#define IDI_ICON_WINLAME                        68
#define IDI_ICON_WORKING                        69
#define IDI_ICON_IDLE                           70
#define IDB_BITMAP_LOGO                         80
#define IDB_BITMAP_BTNICONS                     81
#define IDB_HELP                                82
#define IDR_HTML_ABOUT                          83
#define IDB_BITMAP_FLAGS                        84
#define IDB_BITMAP_TASKS                        85
#define IDR_MAINFRAME                           86
#define ID_ENCODE_FILES                         90
#define ID_ENCODE_CD                            91
#define ID_TASKS_STOP_ALL                       92
#define ID_TASKS_REMOVE_COMPLETED               93
#define ID_SETTINGS_GENERAL                     94
#define ID_SETTINGS_CDREAD                      95
#define ID_VIEW_SWITCH_CLASSIC                  96
#define IDD_MAINDLG                             100
#define IDD_ABOUTDLG                            101
#define IDD_DLG_INPUT                           102
#define IDD_DLG_OUTPUT                          103
#define IDD_DLG_PRESETS                         104
#define IDD_DLG_ENCODE                          109
#define IDD_DLG_OGGVORBIS                       110
#define IDD_DLG_CDRIP                           111
#define IDD_DLG_WAVE                            112
#define IDD_DLG_AAC                             113
#define IDD_DLG_WMA                             114
#define IDD_ERRORDLG                            115
#define IDD_DLG_PRESET_PROPERTY                 116
#define IDD_CDSELECT                            119
#define IDD_DLG_LAME_SIMPLE                     120
#define IDD_FREEDB_LIST                         121
#define IDD_CDRIP_OPTIONS                       122
#define IDD_SETTINGS_GENERAL                    150
#define IDD_SETTINGS_CDREAD                     151
#define IDC_WIZARDPAGE_STATIC_CAPTION           1000
#define IDC_WIZARDPAGE_STATIC_BACKGROUND        1001
#define IDC_WIZARDPAGE_BUTTON_ACTION1           1002
#define IDC_WIZARDPAGE_BUTTON_ACTION2           1003
#define IDC_WIZARDPAGE_STATIC_FRAME             1004
#define IDD_WIZARDPAGE_HOST                     1005
#define IDD_PAGE_INPUT_FILES                    1031
#define IDD_PAGE_INPUT_CD                       1032
#define IDD_PAGE_OUTPUT_SETTINGS                1033
#define IDD_PAGE_PRESET_SELECTION               1034
#define IDD_PAGE_LAME_SETTINGS                  1035
#define IDD_PAGE_LIBSNDFILE_SETTINGS            1036
#define IDD_PAGE_OGGVORBIS_SETTINGS             1037
#define IDD_PAGE_AAC_SETTINGS                   1038
#define IDD_PAGE_WMA_SETTINGS                   1039
#define IDD_PAGE_FINISH                         1040
#define IDC_MDLG_NEXT                           3000
#define IDC_MDLG_BACK                           3001
#define IDC_MDLG_EXIT                           3003
#define IDC_MDLG_CAPTIONBAR                     3004
#define IDC_MDLG_FRAME                          3005
#define IDC_STATIC_WINLAME_LOGO                 3007
#define IDC_STATIC_MAIN_BEVEL                   3008
#define IDC_STATIC_MAIN_BEVEL2                  3009
#define IDC_STATIC_TIMECOUNT                    3010
#define IDC_INPUT_BUTTON_PLAY                   3100
#define IDC_INPUT_LIST_INPUTFILES               3101
#define IDC_INPUT_BUTTON_INFILESEL              3102
#define IDC_INPUT_BUTTON_DELETE                 3103
#define IDC_INPUT_MENU_SELALL                   3104
#define IDC_INPUT_BUTTON_CDRIP                  3105
#define IDC_OUT_COMBO_OUTMODULE                 3200
#define IDC_OUT_DELAFTER                        3201
#define IDC_OUT_OUTPATH                         3202
#define IDC_OUT_SELECTPATH                      3203
#define IDC_OUT_CHECK_FINISHED_ACTION           3204
#define IDC_OUT_COMBO_FINISHED_ACTION           3205
#define IDC_OUT_CHECK_OVERWRITE                 3206
#define IDC_OUT_CREATEPLAYLIST                  3207
#define IDC_OUT_PLAYLISTNAME                    3208
#define IDC_OUT_USE_INDIR                       3209
#define IDC_OUT_BEVEL1                          3210
#define IDC_OUT_BEVEL2                          3211
#define IDC_OUT_BEVEL3                          3212
#define IDC_OUT_CHECK_WARN                      3213
#define IDC_ENC_ENCINFO                         3300
#define IDC_ENC_BEVEL3                          3301
#define IDC_ENC_BEVEL2                          3302
#define IDC_ENC_BEVEL1                          3303
#define IDC_ENC_PROGRESS_FILES                  3304
#define IDC_ENC_PROGRESS_CURRFILE               3305
#define IDC_ENC_START                           3306
#define IDC_ENC_STOP                            3307
#define IDC_ENC_TOTRAY                          3308
#define IDC_ENC_INFO1                           3309
#define IDC_ENC_INFO2                           3310
#define IDC_ENC_INFO3                           3311
#define IDC_ENC_INFO4                           3312
#define IDC_LAME_EDIT_QUALITY                   3400
#define IDC_LAME_SPIN_QUALITY                   3401
#define IDC_LAME_RADIO_TYPE2                    3402
#define IDC_LAME_COMBO_VBR_MODE                 3403
#define IDC_LAME_RADIO_TYPE1                    3404
#define IDC_LAME_CHECK_MONO                     3405
#define IDC_LAME_CHECK_CBR                      3406
#define IDC_LAME_COMBO_ENCODING_QUALITY         3407
#define IDC_LAME_EDIT_BITRATE                   3408
#define IDC_LAME_SPIN_BITRATE                   3409
#define IDC_LAME_CHECK_NOGAP                    3410
#define IDC_LAME_STATIC_VBR_MODE                3411
#define IDC_LAME_CHECK_WRITE_WAVEMP3            3412
#define IDC_LAME_BEVEL1                         3413
#define IDC_LAME_BEVEL2                         3414
#define IDC_LAME_BEVEL3                         3415
#define IDC_OGGV_RADIO_BRMODE1                  3500
#define IDC_OGGV_RADIO_BRMODE2                  3501
#define IDC_OGGV_RADIO_BRMODE3                  3502
#define IDC_OGGV_RADIO_BRMODE4                  3503
#define IDC_OGGV_SLIDER_QUALITY                 3504
#define IDC_OGGV_STATIC_QUALITY                 3505
#define IDC_OGGV_STATIC_BITRATE                 3506
#define IDC_OGGV_STATIC1                        3507
#define IDC_OGGV_STATIC2                        3508
#define IDC_OGGV_STATIC3                        3509
#define IDC_OGGV_STATIC4                        3510
#define IDC_OGGV_STATIC5                        3511
#define IDC_OGGV_EDIT_MIN_BITRATE               3512
#define IDC_OGGV_SPIN_MIN_BITRATE               3513
#define IDC_OGGV_EDIT_NOM_BITRATE               3514
#define IDC_OGGV_SPIN_NOM_BITRATE               3515
#define IDC_OGGV_EDIT_MAX_BITRATE               3516
#define IDC_OGGV_SPIN_MAX_BITRATE               3517
#define IDC_OGGV_BEVEL1                         3518
#define IDC_OGGV_BEVEL2                         3519
#define IDC_OGGV_SPIN_QUICK_QUALITY             3520
#define IDC_WAVE_CHECK_RESAMPLE                 3600
#define IDC_WAVE_RESAMPLEFREQ                   3601
#define IDC_WAVE_CHECK_RAWAUDIO                 3602
#define IDC_WAVE_BEVEL1                         3603
#define IDC_WAVE_CHECK_WAVEX                    3604
#define IDC_WAVE_COMBO_OUTFMT                   3605
#define IDC_WAVE_COMBO_FILEFMT                  3606
#define IDC_WMA_EDIT_BITRATE                    3700
#define IDC_WMA_SPIN_BITRATE                    3701
#define IDC_WMA_RADIO_BRMODE1                   3702
#define IDC_WMA_RADIO_BRMODE2                   3703
#define IDC_WMA_EDIT_QUALITY                    3704
#define IDC_WMA_SPIN_QUALITY                    3705
#define IDC_WMA_BEVEL1                          3706
#define IDC_AAC_EDIT_BITRATE                    3800
#define IDC_AAC_EDIT_BANDWIDTH                  3801
#define IDC_AAC_COMBO_MPEGVER                   3802
#define IDC_AAC_COMBO_OBJTYPE                   3803
#define IDC_AAC_CHECK_MIDSIDE                   3804
#define IDC_AAC_CHECK_USETNS                    3805
#define IDC_AAC_CHECK_USELFE                    3806
#define IDC_AAC_SPIN_BITRATE                    3807
#define IDC_AAC_SPIN_BANDWIDTH                  3808
#define IDC_AAC_BEVEL1                          3809
#define IDC_AAC_CHECK_BANDWIDTH                 3810
#define IDC_AAC_SLIDER_QUALITY                  3811
#define IDC_AAC_STATIC_QUALITY                  3812
#define IDC_AAC_STATIC_KBPS                     3813
#define IDC_AAC_RADIO_BRCMODE1                  3814
#define IDC_AAC_RADIO_BRCMODE2                  3815
#define IDC_AAC_BEVEL2                          3816
#define IDC_CDRIP_CHECK_AUTOSTART_ENC           3900
#define IDC_CDRIP_START                         3901
#define IDC_CDRIP_PROGRESS                      3902
#define IDC_CDRIP_BEVEL1                        3903
#define IDC_CDRIP_LIST_TRACKS                   3904
#define IDC_CDSELECT_LIST_TRACKS                4000
#define IDC_CDSELECT_EDIT_TITLE                 4001
#define IDC_CDSELECT_EDIT_ARTIST                4002
#define IDC_CDSELECT_EDIT_YEAR                  4003
#define IDC_CDSELECT_CHECK_VARIOUS_ARTISTS      4004
#define IDC_CDSELECT_COMBO_GENRE                4005
#define IDC_CDSELECT_COMBO_DRIVES               4006
#define IDC_CDSELECT_BUTTON_FREEDB              4007
#define IDC_CDSELECT_BUTTON_PLAY                4008
#define IDC_CDSELECT_BUTTON_STOP                4009
#define IDC_CDSELECT_STATIC_TITLE               4010
#define IDC_CDSELECT_STATIC_ARTIST              4011
#define IDC_CDSELECT_STATIC_YEAR                4012
#define IDC_CDSELECT_STATIC_GENRE               4013
#define IDC_CDSELECT_BUTTON_OPTIONS             4014
#define IDC_PRE_LIST_PRESET                     4100
#define IDC_PRE_DESC                            4101
#define IDC_PRE_BEVEL1                          4102
#define IDC_ERR_STATIC_ICON                     4200
#define IDC_ERR_STATIC_MODULE                   4201
#define IDC_ERR_STATIC_ERRCODE                  4202
#define IDC_ERR_STATIC_ERRMSG                   4203
#define IDC_ERR_STATIC_FILENAME                 4204
#define IDC_ERR_BUTTON_CONTINUE                 4205
#define IDC_ERR_BUTTON_SKIPFILE                 4206
#define IDC_ERR_BUTTON_STOP                     4207
#define IDC_ERR_BEVEL1                          4208
#define IDC_CDRIP_OPT_CHECK_CDPLAYER_INI        4300
#define IDC_CDRIP_OPT_EDIT_FREEDB_USERNAME      4301
#define IDC_CDRIP_OPT_COMBO_FREEDB_SERVER       4302
#define IDC_CDRIP_OPT_EDIT_TEMP_FOLDER          4303
#define IDC_CDRIP_OPT_BUTTON_TEMP_SELECTPATH    4304
#define IDC_CDRIP_OPT_COMBO_LANGUAGE            4305
#define IDC_CDRIP_OPT_BEVEL1                    4306
#define IDC_CDRIP_OPT_BEVEL2                    4307
#define IDC_FREEDB_LIST_TRACKS                  4400
#define IDC_ABOUT_FRAME                         4401
#define IDC_PROP_LISTBOX                        4404
#define IDC_SETTINGS_COMBO_LANGUAGE             5000
#define ID_TRAY_ABOUT                           30000
#define ID_TRAY_PAUSE                           30001
#define ID_TRAY_START                           30002
#define ID_TRAY_SHOW                            30003
#define ID_TRAY_QUIT                            30004
#define IDS_COMMON_ABOUTBOX                     40000
#define IDS_COMMON_OPTIONS                      40001
#define IDS_COMMON_SELECTDIR                    40002
#define IDS_COMMON_APPMODE_MODERN               40003
#define IDS_ERR_MODULE                          40100
#define IDS_ERR_ERRCODE                         40101
#define IDS_ERR_ERRMSG                          40102
#define IDS_ERR_NOMODULES                       40103
#define IDS_WARNING_LOCAL_PRESETS_XML_FILE_SS   40104
#define IDS_WARN_TRANSCODE                      40105
#define IDS_PRE_DESC_DEFAULT                    40106
#define IDS_AAC_NO_MPEG2_LTP                    40200
#define IDS_OGGV_QUALITY                        40201
#define IDS_OGGV_BITRATE                        40202
#define IDS_DLG_CAP_INPUT                       40203
#define IDS_DLG_CAP_OUTPUT                      40204
#define IDS_DLG_CAP_PRESETS                     40205
#define IDS_DLG_CAP_LAME_SIMPLE                 40206
#define IDS_DLG_CAP_OGGVORBIS                   40207
#define IDS_DLG_CAP_WAVE                        40208
#define IDS_DLG_CAP_AAC                         40209
#define IDS_DLG_CAP_ENCODE                      40210
#define IDS_DLG_CAP_WMA                         40211
#define IDS_DLG_CAP_CDRIP                       40212
#define IDS_DLG_DESC_INPUT                      40300
#define IDS_DLG_DESC_OUTPUT                     40301
#define IDS_DLG_DESC_PRESETS                    40302
#define IDS_DLG_DESC_LAME_SIMPLE                40303
#define IDS_DLG_DESC_OGGVORBIS                  40304
#define IDS_DLG_DESC_WAVE                       40305
#define IDS_DLG_DESC_AAC                        40306
#define IDS_DLG_DESC_ENCODE                     40307
#define IDS_DLG_DESC_WMA                        40308
#define IDS_DLG_DESC_CDRIP                      40309
#define IDS_INPUT_INFILES_SELECT                40400
#define IDS_INPUT_LIST_COLNAME1                 40401
#define IDS_INPUT_LIST_COLNAME2                 40402
#define IDS_INPUT_LIST_COLNAME3                 40403
#define IDS_INPUT_LIST_COLNAME4                 40404
#define IDS_INPUT_NOINFILES                     40406
#define IDS_INPUT_BITRATE_CBR                   40407
#define IDS_INPUT_BITRATE_VBR                   40408
#define IDS_INPUT_BITRATE_ABR                   40409
#define IDS_INPUT_FILTER_PLAYLISTS              40410
#define IDS_INPUT_FILTER_CUESHEETS              40411
#define IDS_INPUT_FILTER_ALLFILES               40412
#define IDS_INPUT_ERROR_OPEN_INPUT_FILE_SSS     40413
#define IDS_INPUT_ERRORS_OCCURED_ADDING         40414
#define IDS_INPUT_TIME_UU                       40415
#define IDS_OUT_OUTDIR_EMPTY                    40600
#define IDS_OUT_CREATE                          40601
#define IDS_OUT_ACTION_EXIT                     40602
#define IDS_OUT_ACTION_SHUTDOWN                 40603
#define IDS_OUT_ACTION_LOGOFF                   40604
#define IDS_OUT_ACTION_HIBERNATE                40605
#define IDS_OUT_ACTION_SUSPEND                  40606
#define IDS_ENC_STOPPED                         40700
#define IDS_ENC_FINISHED                        40701
#define IDS_ENC_U_OF_U                          40702
#define IDS_ENC_FILE_S                          40703
#define IDS_ENC_PERCENT_F                       40704
#define IDS_ENC_REMAINING_UUU                   40705
#define IDS_ENC_TRAY_TOOLTIP                    40706
#define IDS_ENC_TRAY_FINISHED                   40707
#define IDS_HTML_INPUT                          40800
#define IDS_HTML_OUTPUT                         40801
#define IDS_HTML_PRESETS                        40802
#define IDS_HTML_LAME_SIMPLE                    40803
#define IDS_HTML_OGGVORBIS                      40804
#define IDS_HTML_WAVE                           40805
#define IDS_HTML_AAC                            40806
#define IDS_HTML_ENCODE                         40807
#define IDS_HTML_PROPERTYDLG                    40808
#define IDS_HTML_FILEDLG                        40809
#define IDS_HTML_WMA                            40810
#define IDS_HTML_CDRIP                          40811
#define IDS_CDRIP_RANDOM_FREEDB_SERVER          40900
#define IDS_CDRIP_FREEDB_USERNAME_NO_SPACES     40901
#define IDS_CDRIP_COLUMN_NR                     40902
#define IDS_CDRIP_COLUMN_TRACK                  40903
#define IDS_CDRIP_COLUMN_LENGTH                 40904
#define IDS_CDRIP_UNKNOWN_ARTIST                40905
#define IDS_CDRIP_UNKNOWN_TITLE                 40906
#define IDS_CDRIP_TRACK_U                       40907
#define IDS_CDRIP_TRACKTYPE_UNKNOWN             40908
#define IDS_CDRIP_TRACKTYPE_DATA                40909
#define IDS_CDRIP_NO_INTERNET_AVAIL             40910
#define IDS_CDRIP_NO_CDINFO_AVAIL               40911
#define IDS_CDRIP_ERROR_FREEDB                  40912
#define IDS_CDRIP_ERROR_CAPTION                 40913
#define IDS_CDRIP_ERROR_NOCDINFO                40914
#define IDS_CDRIP_ARTIST_VARIOUS                40915
#define IDS_CDRIP_PAGE_COLUMN_TRACK             41000
#define IDS_CDRIP_PAGE_COLUMN_TITLE             41001
#define IDS_CDRIP_PAGE_COLUMN_STATUS            41002
#define IDS_CDRIP_PAGE_STATUS_NOT_PROCESSED     41003
#define IDS_CDRIP_PAGE_STATUS_PROCESSING        41004
#define IDS_CDRIP_PAGE_STATUS_FINISHED          41005
#define IDS_CDRIP_PAGE_ERROR_NO_CD_IN_DRIVE     41006
#define IDS_CDRIP_PAGE_ERROR_WRONG_CD           41007
#define IDS_CDRIP_PAGE_WAVE_OUTPUT_NOT_AVAIL    41008
#define IDS_CDRIP_PAGE_ERROR_CREATE_OUTPUT_FILE_S 41009
#define IDS_AAC_QUALITY_U                       41100
#define IDS_AAC_KBPS_PER_CH_U                   41101
#define IDS_PRESETS_CUSTOM_SETTINGS             41200
#define IDS_LAME_QUALITY_FAST                   41300
#define IDS_LAME_QUALITY_STANDARD               41301
#define IDS_LAME_QUALITY_HIGH                   41302
#define IDS_LAME_BITRATE_MODE_STANDARD          41303
#define IDS_LAME_BITRATE_MODE_FAST              41304
#define IDS_BASS_DLL_ERROR_VERSION_MISMATCH     41400
#define IDS_GENERAL_PLAYLIST_FILENAME           41500
#define IDS_ENCODER_MISSING_INPUT_MOD           41600
#define IDS_ENCODER_ENCODE_INFO                 41601
#define IDS_ENCODER_INPUT_FILE_OPEN_ERROR       41602
#define IDS_ENCODER_OUTPUT_FILE_CREATE_ERROR    41603
#define IDS_ENCODER_ERROR_INIT_DECODER          41604
#define IDS_ENCODER_ERROR_INIT_ENCODER          41605
#define IDS_ENCODER_INVALID_FILE_FORMAT         41606
#define IDS_ENCODER_ERROR_WRITE_OUTPUT          41607
#define IDS_ENCODER_ERROR_GET_FILE_INFOS        41608
#define IDS_ENCODER_INTERNAL_DECODE_ERROR       41609
#define IDS_FILTER_AAC_INPUT                    41700
#define IDS_FILTER_BASS_INPUT                   41701
#define IDS_FILTER_BASS_WMA_INPUT               41702
#define IDS_FILTER_FLAC_INPUT                   41703
#define IDS_FILTER_MAD_MPEG_INPUT               41704
#define IDS_FILTER_MONKEYS_AUDIO_INPUT          41705
#define IDS_FILTER_OGG_VORBIS_INPUT             41706
#define IDS_FILTER_ALL_SUPPORTED                41707
#define IDS_FILTER_SPEEX_INPUT                  41708
#define IDS_FILTER_OPUS_INPUT                   41709
#define IDS_FORMAT_INFO_AAC_INFO                41800
#define IDS_FORMAT_INFO_BASS_INPUT_MUSIC        42001
#define IDS_FORMAT_INFO_BASS_INPUT_AUDIO        42002
#define IDS_FORMAT_INFO_BASS_WMA                42003
#define IDS_FORMAT_INFO_BASS_FILESTREAM         42004
#define IDS_FORMAT_INFO_SNDFILE                 42005
#define IDS_FORMAT_INFO_WAVE_OUTPUT             42006
#define IDS_FORMAT_INFO_LAME                    42007
#define IDS_FORMAT_INFO_LAME_ABR                42008
#define IDS_FORMAT_INFO_LAME_CBR                42009
#define IDS_FORMAT_INFO_LAME_VBR                42010
#define IDS_FORMAT_INFO_MAD_MPEG                42011
#define IDS_FORMAT_INFO_MONKEYS_AUDIO           42012
#define IDS_FORMAT_INFO_OGGV_INPUT_VBR          42013
#define IDS_FORMAT_INFO_OGGV_INPUT_FREE         42014
#define IDS_FORMAT_INFO_OGGV_INPUT_NOMINAL      42015
#define IDS_FORMAT_INFO_BASS_WMA_OUTPUT         42016
#define IDS_FORMAT_INFO_FLAC_INPUT              42017
#define IDS_FORMAT_INFO_OGGV_OUTPUT_QUALITY     42018
#define IDS_FORMAT_INFO_OGGV_OUTPUT_VBR         42019
#define IDS_FORMAT_INFO_OGGV_OUTPUT_ABR         42020
#define IDS_FORMAT_INFO_OGGV_OUTPUT_CBR         42021
#define IDS_FORMAT_INFO_AAC_OUTPUT              42022
#define IDS_FORMAT_INFO_SPEEX_INPUT             42023
#define IDS_FORMAT_INFO_OPUS_INPUT              42024
#define IDS_APP_CAPTION                         50000
#define IDS_LANG_ENGLISH                        50001
#define IDS_LANG_NATIVE                         50002
